@echo on

cmake -S %SRC_DIR% -Bbuild ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ^
    -DBUILD_SHARED_LIBS=ON ^
    -DBUILD_JAVA=False ^
    -DORC_PACKAGE_KIND=vcpkg ^
    -DBUILD_LIBHDFSPP=NO ^
    -DBUILD_CPP_TESTS=OFF ^
    -DBUILD_TOOLS=OFF ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_CXX_FLAGS="%CMAKE_CXX_FLAGS% /DPROTOBUF_USE_DLLS" ^
    -GNinja
if ERRORLEVEL 1 EXIT 1

cmake --build build --target install
if ERRORLEVEL 1 EXIT 1
