cmake -S %SRC_DIR% -Bbuild ^
    -DCMAKE_PREFIX_PATH=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ^
    -DBUILD_SHARED_LIBS=ON ^
    -DBUILD_JAVA=False ^
    -DLZ4_HOME=%LIBRARY_PREFIX% ^
    -DZLIB_HOME=%LIBRARY_PREFIX% ^
    -DZSTD_HOME=%LIBRARY_PREFIX% ^
    -DSTOP_BUILD_ON_WARNING=OFF ^
    -DProtobuf_ROOT=%LIBRARY_PREFIX% ^
    -DPROTOBUF_HOME=%LIBRARY_PREFIX% ^
    -DPROTOBUF_EXECUTABLE=%BUILD_PREFIX%\Library\bin\protoc.exe ^
    -DSNAPPY_HOME=%LIBRARY_PREFIX% ^
    -DBUILD_LIBHDFSPP=NO ^
    -DBUILD_CPP_TESTS=OFF ^
    -DBUILD_TOOLS=OFF ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_CXX_FLAGS="%CMAKE_CXX_FLAGS% /DPROTOBUF_USE_DLLS" ^
    -GNinja
if ERRORLEVEL 1 EXIT 1

cmake --build build --target install
if ERRORLEVEL 1 EXIT 1
