{% set version = "1.6.4" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: ceea9849277354cffb37853b7f47ea96898c3e716e0803a597ca657cdb59e43c
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
  run:
    - libprotobuf

test:
  commands:
    - test -f $PREFIX/lib/liborc.a  # [unix]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC

extra:
  recipe-maintainers:
    - wesm
    - xhochy
