{% set version = "1.6.3" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: 38b9da9ca771d26877cae5b8da55aa1d1bf1ed515723f9cfdcba49d619396bc4
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - 0001-Deactivate-aggressive-failures-on-warnings.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - libprotobuf-static
    - lz4-c

test:
  commands:
    - test -f $PREFIX/lib/liborc.a  # [unix]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC

extra:
  recipe-maintainers:
    - wesm
    - xhochy
