{% set version = "2.1.3" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: db56c6173df2e937ec9e2c282748e27897d82c1422e7d7c4d34ab626c18338b2
  patches:
    - patches/0001-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch
    - patches/0002-Allow-user-to-override-path-to-protoc.patch
    - patches/0003-add-missing-include-for-protobuf-types.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("orc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    # `protoc` is also used for building
    - libprotobuf
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
    - zstd
  run:
    # orc >=2.0.1 will prefer $CONDA_PREFIX/share/zoneinfo for tzdb
    - tzdata

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/liborc.so              # [linux]
    - test -f $PREFIX/lib/liborc.dylib           # [osx]
    - if not exist %LIBRARY_BIN%\orc.dll exit 1  # [win]
    # import library for the DLL
    - if not exist %LIBRARY_LIB%\orc.lib exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/liborc.a             # [not win]

    # headers
    - test -f $PREFIX/include/orc/Common.hh            # [unix]
    - if not exist %LIBRARY_INC%\orc\Common.hh exit 1  # [win]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC
  dev_url: https://github.com/apache/orc

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - nehaljwani
