{% set version = "1.8.3" %}

package:
  name: orc
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/orc/orc-{{ version }}/orc-{{ version }}.tar.gz
  sha256: a78678ec425c8129d63370cb8a9bacb54186aa66af1e2bec01ce92e7eaf72e20
  patches:
    # ORC builds by default with -Werror but some dependencies omit warnings.
    # This deactivates -Werror
    - patches/0001-Deactivate-aggressive-failures-on-warnings.patch
    - patches/0002-Don-t-force-orc-to-be-a-static-library-let-end-user-.patch
    - patches/0003-CMake-Add-more-hints-for-libraries-on-Windows.patch
    - patches/0004-don-t-force-lib-destination.patch
    - patches/0005-ORC-1301-C-Enforce-C-17.patch
    - patches/0006-Check-for-protobuf-config-based-module.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("orc", max_pin="x.x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja       # [unix]
    # `protoc` is also used for building
    - libprotobuf
    - cmake
  host:
    - zlib
    - snappy
    - libprotobuf
    - lz4-c
    - zstd

test:
  commands:
    # shared libraries
    - test -f $PREFIX/lib/liborc.so              # [linux]
    - test -f $PREFIX/lib/liborc.dylib           # [osx]
    - if not exist %LIBRARY_BIN%\orc.dll exit 1  # [win]
    # import library for the DLL
    - if not exist %LIBRARY_LIB%\orc.lib exit 1  # [win]

    # absence of static libraries
    - test ! -f $PREFIX/lib/liborc.a             # [not win]

    # headers
    - test -f $PREFIX/include/orc/Common.hh            # [unix]
    - if not exist %LIBRARY_INC%\orc\Common.hh exit 1  # [win]

about:
  home: http://github.com/apache/orc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: C++ libraries for Apache ORC
  dev_url: https://github.com/apache/orc

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - nehaljwani
